spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/healthsys}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8086
