global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8081']

  - job_name: patient-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['patient-service:8082']

  - job_name: triage-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['triage-service:8083']

  - job_name: record-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['record-service:8084']

  - job_name: bed-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['bed-service:8085']

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['notification-service:8086']

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: analytics-service
    metrics_path: /metrics
    static_configs:
      - targets: ['analytics-service:8088']

  - job_name: ai-service
    metrics_path: /metrics
    static_configs:
      - targets: ['ai-service:8087']
