apiVersion: v1
kind: ConfigMap
metadata:
  name: healthsys-config
  namespace: healthsys
data:
  # Database (Java services)
  DB_URL: jdbc:postgresql://postgres:5432/healthsys
  DB_USERNAME: myuser

  # Database (Python services)
  DB_HOST: postgres
  DB_NAME: healthsys
  DB_USER: myuser

  # Kafka
  KAFKA_SERVERS: kafka:9092

  # Redis
  REDIS_HOST: redis

  # CORS — origens permitidas pelo api-gateway
  ALLOWED_ORIGINS: https://healthsys.vercel.app,https://healthsys-olrtkhpv6-augusto-soares-projects-26a59e8a.vercel.app

  # Downstream service URLs (api-gateway)
  USER_SERVICE_URL: http://user-service:8081
  PATIENT_SERVICE_URL: http://patient-service:8082
  TRIAGE_SERVICE_URL: http://triage-service:8083
  RECORD_SERVICE_URL: http://record-service:8084
  BED_SERVICE_URL: http://bed-service:8085
  NOTIFICATION_SERVICE_URL: http://notification-service:8086
  AI_SERVICE_URL: http://ai-service:8087
  ANALYTICS_SERVICE_URL: http://analytics-service:8088
