apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: healthsys
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: ghcr.io/soaresaugustof/healthsys-analytics-service:latest
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: healthsys-config
            - secretRef:
                name: healthsys-secret
          env:
            - name: PORT
              value: "8088"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: 8088
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: healthsys
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8088
      targetPort: 8088
